name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug", "triage"]
assignees:
  - Poly-Pixel
body: 
  - type: markdown
    attributes:
      value: Fill out the fields below, and it will be reviewed as soon as possible. Remember to follow the Code of Conduct
  - type: input
    id: page
    attributes:
      label: Page
      description: What page did the bug occur on?
      placeholder: ex. /dashboard
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What happened? Please be as clear as possible
      placeholder: ex. I got an error message...
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system did you see the bug on?
      placeholder: ex. Windows 10
  - type: input
    id: browser
    attributes:
      label: Web Browser
      description: What web browser did you see the bug on? Include the version
      placeholder: ex. Google Chrome 96
      
    
